version: '3.7'
services:
  postgresql:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=pronoundb_bot
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - pronoundb_bot_psql:/var/lib/postgresql/data
  redis:
    image: 'redis:alpine'
volumes:
  pronoundb_bot_psql:
